//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spor_Salonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aletler
    {
        public int aletid { get; set; }
        public Nullable<int> kategoriid { get; set; }
        public string aletad { get; set; }
        public string aletaciklama { get; set; }
        public string foto { get; set; }
    
        public virtual kategori kategori { get; set; }
    }
}
