//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spor_Salonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class beslenme
    {
        public int id { get; set; }
        public Nullable<int> kategorid { get; set; }
        public Nullable<int> gunid { get; set; }
        public string aciklamas { get; set; }
        public string aciklamao { get; set; }
        public string aciklamaa { get; set; }
    
        public virtual gun gun { get; set; }
        public virtual kategori2 kategori2 { get; set; }
    }
}
