//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spor_Salonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class giris
    {
        public int id { get; set; }
        public string kadi { get; set; }
        public string sifre { get; set; }
        public string yetki { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string tel { get; set; }
    }
}
