//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spor_Salonu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sporsalonuEntities1 : DbContext
    {
        public sporsalonuEntities1()
            : base("name=sporsalonuEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<giris> giris { get; set; }
        public virtual DbSet<aletler> aletler { get; set; }
        public virtual DbSet<kategori> kategori { get; set; }
        public virtual DbSet<beslenme> beslenme { get; set; }
        public virtual DbSet<gun> gun { get; set; }
        public virtual DbSet<kategori2> kategori2 { get; set; }
    }
}
